[tool.poetry]
name = "test-project-13"
version = "0.1.0"
description = ""
authors = ["Ivan Glushenkov <glushman966@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
